config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('monitoring.urls')),
    path('upload/', include('input.urls')),
    path('recovery/', include('recovery.urls')),
    path('mgt/', include('remgt.urls')),
]

input/urls.py
from django.urls import path
from .views import *
from .models import Files

app_name = 'input'

urlpatterns=[
    path('', file_list, name='file_list'),
    path('upload/', FileUploadView.as_view(), name='file_upload'),
]

monitoring/urls.py
from django.urls import path
from .views import *
from .views2 import *
from .views3 import *

app_name = 'monitoring'

urlpatterns=[
    path('', ban_board, name='ban_board'),
    path('data/', search_list, name='search'),
    path('data/detail/<int:pk>/', DataDetailView.as_view(), name='detail'),
    path('data/update/<int:pk>/', DataUpdatelView.as_view(), name='data_update'),
    path('mass/', MassListView.as_view(), name='mass_board'),
    path('mass/add/', MassCreateView.as_view(), name='add'),
    path('mass/update/<int:pk>/', MassUpdateView.as_view(), name='update'),
    path('mass/delete/<int:pk>/', MassDeleteView.as_view(), name='delete'),
    #path('mi/', mibe_board, name='mibe_board'),
    #path('be/', be_board, name='be_board'),
    path('loading/', loading, name='loading')
]

recovery/urls.py
from django.urls import path
from .views import *

app_name = 'recovery'

urlpatterns=[
    path('<int:mn>/', re_board, name='re_board'),
    path('create/<int:pk>/', recovery_create, name='re_create'),
    path('update/<int:pk>/', RecoveryUpdatelView.as_view(), name='re_update'),
    path('delete/<int:pk>/', recovery_delete, name='re_delete'),
    path('detail/<int:pk>/', recovery_detail, name='re_detail'),
    path('mgt/detail/<int:pk>/', mgt_detail, name='mgt_detail'),
    path('mgt/create/<int:pk>/', mgt_create, name='mgt_create'),
    path('mgt/update/<int:pk>/', MgtUpdatelView.as_view(), name='mgt_update'),
    path('mgt/delete/<int:pk>/', mgt_delete, name='mgt_delete'),
]

recovery/models.py
from django.db import models
from monitoring.models import Data, MassBoard
# Create your models here.


class Recovery(models.Model):
    car_data = models.ForeignKey(Data, on_delete=models.PROTECT)
    car_num = models.CharField(max_length=10, null=True, verbose_name="차량번호")
    car_date = models.DateField(null=True, blank=True, verbose_name="반납일자")
    car_model = models.CharField(max_length=100, null=True, blank=True, verbose_name="모델")
    appraiser = models.CharField(max_length=10, null=True, blank=True, verbose_name="반납평가사")
    ap_grade = models.IntegerField(default=5, verbose_name="평가점수")
    rq_ex = models.BooleanField(default=False, verbose_name="보험접수유무")
    price_ex = models.BooleanField(default=False, verbose_name="일반수리유무")
    outstanding1 = models.BooleanField(default=False, verbose_name="보험미처리")
    outstanding2 = models.BooleanField(default=False, verbose_name="일반미처리")
    prog = models.BooleanField(default=False, verbose_name="미납처리")
    re_num = models.IntegerField(default=0, null=True, blank=True, verbose_name="원상회복건수")
    rp_num = models.IntegerField(default=0, null=True, blank=True, verbose_name="보험접수건수")
    re_part = models.CharField(max_length=100, null=True, blank=True, verbose_name="원상회복부위")
    rq_number = models.CharField(max_length=50, null=True, blank=True, verbose_name="보험접수번호")
    rq_price = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="수리청구금액")
    cus_number = models.CharField(max_length=100, null=True, blank=True, verbose_name="고객연락처")
    created = models.DateTimeField(auto_now_add=True, verbose_name="등록일자")
    text = models.TextField(blank=True, null=True, verbose_name="비고")

    class Meta:
        ordering = ['-created']
        verbose_name = '원상회복관리'
        verbose_name_plural = '원상회복관리'


class RecoveryMgt(models.Model):
    R_data = models.ForeignKey(Recovery, on_delete=models.CASCADE)
    car_num = models.CharField(max_length=10, null=True, verbose_name="차량번호")
    car_date = models.DateField(null=True, blank=True, verbose_name="반납일자")
    receive1 = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="입금액1")
    redate1 = models.DateField(blank=True, null=True, verbose_name="입금날짜1")
    receive2 = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="입금액2")
    redate2 = models.DateField(blank=True, null=True, verbose_name="입금날짜2")
    receive3 = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="입금액3")
    redate3 = models.DateField(blank=True, null=True, verbose_name="입금날짜3")
    receive4 = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="입금액4")
    redate4 = models.DateField(blank=True, null=True, verbose_name="입금날짜4")
    receive5 = models.BigIntegerField(default=0, null=True, blank=True, verbose_name="입금액5")
    redate5 = models.DateField(blank=True, null=True, verbose_name="입금날짜5")
    created = models.DateTimeField(auto_now_add=True, verbose_name="등록일자")
    updated = models.DateTimeField(auto_now=True, verbose_name="수정일자")
    req_date = models.DateField(blank=True, null=True, verbose_name="매입보류요청일")
    req_cdate = models.DateField(blank=True, null=True, verbose_name="보류해지요청일")

    class Meta:
        ordering = ['-created']

recovery/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import *
from monitoring.models import *
from django.db.models import Count, Sum
from datetime import datetime

@login_required

def re_board(request, mn):
    counts=[]
    count = {}

    a = datetime.now().year
    b = request.GET.get("year",a)
    if mn == 0:
        c = Recovery.objects.filter(rq_ex=1, car_date__year=b).aggregate(Count('rq_ex'))
        d = Recovery.objects.filter(price_ex=1, car_date__year=b).aggregate(Count('price_ex'))
        dd = Recovery.objects.filter(price_ex=1, car_date__year=b).aggregate(Sum('rq_price'))
    else:
        c = Recovery.objects.filter(rq_ex=1, car_date__year=b, car_date__month=mn).aggregate(Count('rq_ex'))
        d = Recovery.objects.filter(price_ex=1, car_date__year=b, car_date__month=mn).aggregate(Count('price_ex'))
        dd = Recovery.objects.filter(price_ex=1, car_date__year=b, car_date__month=mn).aggregate(Sum('rq_price'))
    e = Recovery.objects.filter(outstanding1=1, car_date__year=b).aggregate(Count('outstanding1'))
    f = Recovery.objects.filter(outstanding2=1, car_date__year=b).aggregate(Count('outstanding2'))
    ff = Recovery.objects.filter(outstanding2=1, car_date__year=b).aggregate(Sum('rq_price'))
    count['year'] = b
    i = 1
    for i in range(1,13):
        g = Recovery.objects.filter(rq_ex=1, car_date__year=b, car_date__month=i).aggregate(Count('rq_ex'))
        h = Recovery.objects.filter(price_ex=1, car_date__year=b, car_date__month=i).aggregate(Count('price_ex'))
        k = 'm' + str(i)
        l = 'n' + str(i)
        count[k] = g['rq_ex__count']
        count[l] = h['price_ex__count']

    count['rq_ex'] = c['rq_ex__count']
    count['price_ex'] = d['price_ex__count']
    count['price1'] = dd['rq_price__sum']
    try:
        count['avg'] = int(dd['rq_price__sum'] / d['price_ex__count'])
    except:
        count['avg'] = None
    count['out1'] = e['outstanding1__count']
    count['out2'] = f['outstanding2__count']
    count['price2'] = ff['rq_price__sum']
    count['price3'] = 0
    count['price4'] = 0

    lists = []
    list = {}

    outs = Recovery.objects.filter(outstanding1=1, car_date__year=b)
    for out in outs:
        try:
            list['id'] = out.id
            list['car_num'] = out.car_num
            list['car_date'] = out.car_date
            list['model'] = out.car_model
            list['rq_ex'] = out.rq_ex
            list['num'] = out.rp_num
            list['car_data'] = out.car_data_id
            lists.append(list)
            list = {}
        except:
            None

    outss = Recovery.objects.filter(outstanding2=1, car_date__year=b)
    for out in outss:
        try:
            list['id'] = out.id
            list['car_num'] = out.car_num
            list['car_date'] = out.car_date
            list['model'] = out.car_model
            list['price_ex'] = out.price_ex
            list['price'] = out.rq_price
            try:
                RM = RecoveryMgt.objects.get(R_data_id=list['id'])
                if RM.receive1 is None: RM.receive1 = 0
                if RM.receive2 is None: RM.receive2 = 0
                if RM.receive3 is None: RM.receive3 = 0
                list['in_price'] = RM.receive1 + RM.receive2 + RM.receive3
                list['miss'] = list['price'] - list['in_price']
            except:
                list['in_price'] = 0
                list['miss'] = list['price'] - list['in_price']
            list['car_data'] = out.car_data_id
            count['price3'] += list['miss']
            lists.append(list)
            list = {}
        except:
            None
    outsss = Recovery.objects.filter(prog=1, car_date__year=b)
    for out in outsss:
        try:
            list['id'] = out.id
            list['car_num'] = out.car_num
            list['car_date'] = out.car_date
            list['model'] = out.car_model
            list['prog'] = out.prog
            list['price'] = out.rq_price
            try:
                RM = RecoveryMgt.objects.get(R_data_id=list['id'])
                if RM.receive1 is None: RM.receive1 = 0
                if RM.receive2 is None: RM.receive2 = 0
                if RM.receive3 is None: RM.receive3 = 0
                list['in_price'] = RM.receive1 + RM.receive2 + RM.receive3
                list['miss'] = list['price'] - list['in_price']
            except:
                list['in_price'] = 0
                list['miss'] = list['price'] - list['in_price']
            list['car_data'] = out.car_data_id
            count['price4'] += list['miss']
            lists.append(list)
            list = {}
        except:
            None

    counts.append(count)
    lists = sorted(lists, key=lambda x:x['id'], reverse=True)

    return render(request, 'recovery/re_board.html', {'counts':counts, 'lists':lists, 'mn':mn})

def recovery_create(request, pk):

    data = Data.objects.get(id=pk)

    if request.method == 'POST':
        a = request.POST["aa"]
        b = request.POST["bb"]
        c = request.POST["cc"]
        d = request.POST["dd"]
        e = request.POST["ee"]
        h = request.POST["hh"]
        l = request.POST["ll"]
        m = request.POST["mm"]
        n = request.POST["nn"]

        car_num = data.car_num2
        car_date = data.a_rdate
        car_model = data.car_type
        appraiser = a
        ap_grade = b

        if c == "":
            re_num = 0
        else:
            re_num = c

        if d == "":
            rp_num = 0
            rq_ex = False
            out1 = False
        else:
            rp_num = d
            rq_ex = True
            out1 = True

        re_part = e

        if h == "":
            rq_number = None
        else:
            rq_number = h
            out1 = False

        if l =="":
            rq_price = 0
            price_ex = False
            out2 = False
            prog = False
        else:
            rq_price = l
            price_ex = True
            out2 = True
            prog = False

        cus_number = m
        text = n.replace("/r/n","<br>")

        save_data = Recovery(
            car_data = data,
            car_num = car_num,
            car_date = car_date,
            car_model = car_model,
            appraiser = appraiser,
            ap_grade = ap_grade,
            rq_ex = rq_ex,
            price_ex=price_ex,
            outstanding1 = out1,
            outstanding2 = out2,
            prog = prog,
            re_num = re_num,
            rp_num =rp_num,
            re_part = re_part,
            rq_number = rq_number,
            rq_price = rq_price,
            cus_number = cus_number,
            text = text
        )
        save_data.save()

        m_data = Data.objects.get(id=pk)
        m_data.ex = True
        m_data.save()

        return redirect('/recovery/0')

    return render(request,'recovery/re_create.html', {'data':data})


from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class RecoveryUpdatelView(UpdateView):
    model = Recovery
    fields = ['appraiser', 'ap_grade', 're_part', 'rq_ex', 're_num', 'rp_num', 'rq_number', 'outstanding1',  'price_ex', 'rq_price', 'outstanding2', 'prog', 'cus_number', 'text']
    success_url = "/recovery/0"
    template_name = 'recovery/re_update.html'


def recovery_delete(request, pk):
    rdata = Recovery.objects.get(id=pk)
    pk2 = int(rdata.car_data_id)
    data = Data.objects.get(id=pk2)

    rdata.delete()
    data.ex = False
    data.save()

    return redirect('/recovery/0')

def recovery_detail(request, pk):
    data = Recovery.objects.get(car_data_id=pk)
    pk2 = data.id
    data3 = {}
    try:
        data2 = RecoveryMgt.objects.get(R_data_id=pk2)

        if data2.receive1:
            data3['total'] = data2.receive1
            data3['miss'] = data.rq_price - data3['total']

        if data2.receive2:
            data3['total'] += data2.receive2
            data3['miss'] = data.rq_price - data3['total']
        if data2.receive3:
            data3['total'] += data2.receive3
            data3['miss'] = data.rq_price - data3['total']

    except:
        data2 = None
        data3['miss'] = data.rq_price

    return render(request, 'recovery/re_detail.html', {'data':data, 'data2':data2, 'data3':data3})

def mgt_detail(request, pk):
    try:
        data = RecoveryMgt.objects.get(R_data_id=pk)
        data3 = {}
        if data.receive1:
            data3['total'] = data.receive1
        if data.receive2:
            data3['total'] += data.receive2
        if data.receive3:
            data3['total'] += data.receive3
        data3['totaln'] = -data3['total']
        data2 = Recovery.objects.get(id=pk)
    except:
        data = None
        data3 = None
        data2 = Recovery.objects.get(id=pk)
    return render(request, 'recovery/mgt_detail.html', {'data':data,'data2':data2, 'data3':data3})


def mgt_create(request, pk):

    data = Recovery.objects.get(id=pk)
    pk2 = data.car_data_id
    car = Data.objects.get(id=pk2)

    if request.method == 'POST':
        a = request.POST["aa"]
        b = request.POST["bb"]
        c = request.POST["cc"]
        d = request.POST["dd"]
        e = request.POST["ee"]
        f = request.POST["ff"]
        g = request.POST["gg"]
        h = request.POST["hh"]

        R_data_id = data.id
        car_num = data.car_num
        car_date = data.car_date

        if a == "":
            receive1 = None
        else:
            receive1 = a
        if b == "":
            redate1 = None
        else:
            redate1 = b
        if c == "":
            receive2 = None
        else:
            receive2 = c
        if d == "":
            redate2 = None
        else:
            redate2 = d
        if e == "":
            receive3 = None
        else:
            receive3 = e
        if f == "":
            redate3 = None
        else:

recovery/templates/recovery/mgt_detail.html
{% extends "layout.html" %}

{% block title %}입금내역관리{% endblock %}

{% block content %}
{% load humanize %}
<p></p>
<div class="container">
    <h4>입금내역관리</h4>
    {% if data is None %}
    <a class="btn btn-success btn-sm text-white" href="{% url 'recovery:mgt_create' pk=data2.id %}" role="button">신규등록</a>
    {% else %}
    <a class="btn btn-primary btn-sm text-white" href="{% url 'recovery:mgt_update' pk=data.id %}" role="button">업데이트</a>
    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">삭제</button>
    {% endif %}
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">삭제 하시겠습니까?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                <a class="btn btn-danger" role="button" href="{% url 'recovery:mgt_delete' pk=data2.id %}">삭제</a>
              </div>
            </div>
          </div>
        </div>

</div>

<p></p>
<div class="container">
<dl class="row">
    <dt class="col-sm-3">(반납) 차량번호</dt>
    <dd class="col-sm-9">{{data2.car_num}}</dd>
    <dt class="col-sm-3">차종(모델)</dt>
    <dd class="col-sm-9">{{data2.car_model}}</dd>
    <dt class="col-sm-3">반납일</dt>
    <dd class="col-sm-9">{{data2.car_date|date:'Y-m-d'}}</dd>
</dl>
</div>
<div class="container">
<dl class="row">
    <dt class="col-sm-3">청구금액</dt>
    <dd class="col-sm-9">{{data2.rq_price|intcomma}} 원</dd>
</dl>
</div>

{% if data is None %}
<div class="container">
<div class="col-md-6 alert alert-danger" role="alert">입금내역 데이터가 없습니다.</div>
</div>
{% else %}
<p></p>
<div class="container">
<dl class="row">
    <dt class="col-sm-3">입금액 합계<a class="text-danger"> (미수금액)</a></dt>
    {% if data3.total is None %}
    <dd class="col-sm-9">입금액이 없습니다.<a class="text-danger">(0)</a></dd>
    {% else %}
    <dd class="col-sm-9">{{data3.total|intcomma}} 원<a class="text-danger"> ({{data2.rq_price|add:data3.totaln|intcomma}})</a></dd>
    {% endif %}
</dl>
</div>
<div class="container">
<dl class="row">
    <dt class="col-sm-1"></dt>
    <dd class="col-sm-8">
    <dl class="row">
        <dt class="col-sm-3">입금액1</dt>
        <dd class="col-sm-9">{{data.receive1|intcomma}}</dd>
        <dt class="col-sm-3">입금일자1</dt>
        <dd class="col-sm-9">{{data.redate1|date:'Y-m-d'}}</dd>
        <dt class="col-sm-3">입금액2</dt>
        <dd class="col-sm-9">{{data.receive2|intcomma}}</dd>
        <dt class="col-sm-3">입금일자2</dt>
        <dd class="col-sm-9">{{data.redate2|date:'Y-m-d'}}</dd>
        <dt class="col-sm-3">입금액3</dt>
        <dd class="col-sm-9">{{data.receive3|intcomma}}</dd>
        <dt class="col-sm-3">입금일자3</dt>
        <dd class="col-sm-9">{{data.redate3|date:'Y-m-d'}}</dd>
    </dl>
    </dd>
</dl>
</div>
<!--
<div class="container">
<dl class="row">
    <dt class="col-sm-3">매입보류 유/무</dt>
    <dd class="col-sm-9 text-danger">Yes</dd>
    <dt class="col-sm-3">청구 금액</dt>
    <dd class="col-sm-9">{{data.rq_price|intcomma}}</dd>
</dl>
</div>
-->
{% endif %}
<div class="container">
<dl class="row">
    <dt class="col-sm-3">비고</dt>
    <dd class="col-sm-9">{{data2.text|linebreaksbr}}</dd>
</dl>
</div>
{% endblock %}

recovery/templates/recovery/mgt_update.html
{% extends "layout.html" %}
{% block title %}
입금내역 수정
{% endblock %}

{% block content %}
{% load humanize %}
<p></p>
<div class="container">
<div class="col-md-6 alert alert-danger">
    <h4>입금내역 수정</h4>
</div>
</div>
<p></p>
<div class="container">
<dl class="row">
    <dt class="col-sm-3">(반납) 차량번호</dt>
    <dd class="col-sm-9">{{recoverymgt.car_num}}</dd>
    <dt class="col-sm-3">반납일</dt>
    <dd class="col-sm-9">{{recoverymgt.car_date|date:'Y-m-d'}}</dd>
</dl>
</div>

<p></p>
<div class="container">
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update" class="btn btn-info btn-sm">
</form>
</div>
{% endblock %}

recovery/templates/recovery/re_board.html
{% extends "layout.html" %}
{% block title %}
원상회복관리
{% endblock %}

{% block content %}
{% load humanize %}
<p></p>
<div class="col-md-4">

        <form class="form-inline" action="{%url 'monitoring:search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="차량번호" aria-label="Search" name="number" value="{{number}}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
        </form>
</div>
<p></p>

{% for count in counts %}
<p></p>
<div class="col-md-2">
<div class="btn-group">
    <form method="get">
        <button class="btn btn-outline-primary" type="submit" name="year" value="2019">2019년</button>
    </form>
    <form method="get">
        <button class="btn btn-outline-primary" type="submit" name="year" value="2020">2020년</button>
    </form>
</div>
<div class="btn-group">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      월
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'recovery:re_board' mn=0%} ">전체</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=1%}">1월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=2%}">2월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=3%}">3월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=4%}">4월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=5%}">5월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=6%}">6월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=7%}">7월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=8%}">8월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=9%}">9월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=10%}">10월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=11%}">11월</a>
      <a class="dropdown-item" href="{% url 'recovery:re_board' mn=12%}">12월</a>

  </div>
</div>
</div>
<p></p>


<div id="container"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>

<div class="col-md-2">
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: '{{count.year}}년 원상회복 현황'
        },
        xAxis: {
            categories: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']
        },
        series: [{
            name: '보험수리(건)',
            data: [{{count.m1}},{{count.m2}},{{count.m3}},{{count.m4}},{{count.m5}},{{count.m6}},{{count.m7}},{{count.m8}},{{count.m9}},{{count.m10}},{{count.m11}},{{count.m12}}]
        }, {
            name: '일반수리(건)',
            data: [{{count.n1}},{{count.n2}},{{count.n3}},{{count.n4}},{{count.n5}},{{count.n6}},{{count.n7}},{{count.n8}},{{count.n9}},{{count.n10}},{{count.n11}},{{count.n12}}]
        }]
    });
</script>
</div>

<p></p>

<div class="container">
<span style="font-size:1.0em">
<dl class="row">
    {% if mn == 0 %}
    <dt class="col-sm-3">원상회복 발생 총 건수<p>(전체)</p></dt>
    {% else %}
    <dt class="col-sm-3">원상회복 발생 총 건수<p class="text-primary">( {{mn}} 월)</p></dt>
    {% endif %}
    <dd class="col-sm-9">
        <dl class="row">
          <dt class="col-sm-3">보험수리</dt>
          <dd class="col-sm-9">{{count.rq_ex|intcomma}} 건</dd>

          <dt class="col-sm-3">일반수리</dt>
          <dd class="col-sm-9">{{count.price_ex|intcomma}} 건</dd>

          <dt class="col-sm-3">(청구총액)</dt>
          <dd class="col-sm-9">{{count.price1|intcomma}} 원 ( 평균 {{count.avg|intcomma}} 원)</dd>
        </dl>
    </dd>

    <dt class="col-sm-3">미처리 건수</dt>
    <dd class="col-sm-9">
      <dl class="row">
          <dt class="col-sm-3">보험수리</dt>
          <dd class="col-sm-9"><p class="text-danger">{{count.out1|intcomma}} 건 </p></dd>

          <dt class="col-sm-3">일반수리</dt>
          <dd class="col-sm-9"><p class="text-danger">{{count.out2|intcomma}} 건 ({{count.price2|intcomma}} 원)</p></dd>

          <dt class="col-sm-3">(미수총액)</dt>
          <dd class="col-sm-9"><p class="text-danger">{{count.price3|intcomma}} 원</p></dd>

          <dt class="col-sm-3">(미납처리 금액)</dt>
         <dd class="col-sm-9"><p class="text-danger">{{count.price4|intcomma}} 원</p></dd>
      </dl>
    </dd>
</dl>
</span>
</div>
{% endfor %}

<p></p>
<div class="container">
    <div class="alert alert-success" role="alert">
        <strong>원상회복 미처리 데이터 리스트</strong>
    </div>
</div>
<p></p>

<div class="container">
<table class="table table-striped">
    {% if lists %}
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">(반납)차량번호</th>
            <th scope="col">차종</th>
            <th scope="col">반납일자</th>
            <th scope="col">보험 건수</th>
            <th scope="col">일반수리 청구금액</th>
            <th scope="col">미수금액</th>
            <th scope="col">미납처리 사항</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for list in lists %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{list.car_num}}</td>
                <td>{{list.model}}</td>
                <td>{{list.car_date|date:'Y-m-d'}}</td>
                {% if list.rq_ex %}
                <td><a class="text-danger">{{list.num}}</a></td>
                {% else %}
                <td><a class="text-info">No</a></td>
                {% endif %}

                <td><a class="text-danger">{{list.price|intcomma}}</a></td>
                <td><a class="text-danger">{{list.miss|intcomma}}</a></td>


                {% if list.prog %}
                <td><span class="badge badge-pill badge-danger">미납처리</span></td>
                {% else %}
                <td><a class="text"></a></td>
                {% endif %}
                <td><a href="{% url 'recovery:re_detail' pk=list.car_data %}" class="btn btn-dark btn-sm">관리</a></td>
            </tr>
        {% endfor %}
    </tbody>
    {% endif %}
</table>
</div>



<p></p>
{% endblock %}