config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('monitoring.urls')),
    path('upload/', include('input.urls')),
    path('recovery/', include('recovery.urls')),
    path('mgt/', include('remgt.urls')),
]

input/urls.py
from django.urls import path
from .views import *
from .models import Files

app_name = 'input'

urlpatterns=[
    path('', file_list, name='file_list'),
    path('upload/', FileUploadView.as_view(), name='file_upload'),
]

recovery/urls.py
from django.urls import path
from .views import *

app_name = 'recovery'

urlpatterns=[
    path('<int:mn>/', re_board, name='re_board'),
    path('create/<int:pk>/', recovery_create, name='re_create'),
    path('update/<int:pk>/', RecoveryUpdatelView.as_view(), name='re_update'),
    path('delete/<int:pk>/', recovery_delete, name='re_delete'),
    path('detail/<int:pk>/', recovery_detail, name='re_detail'),
    path('mgt/detail/<int:pk>/', mgt_detail, name='mgt_detail'),
    path('mgt/create/<int:pk>/', mgt_create, name='mgt_create'),
    path('mgt/update/<int:pk>/', MgtUpdatelView.as_view(), name='mgt_update'),
    path('mgt/delete/<int:pk>/', mgt_delete, name='mgt_delete'),
]

remgt/urls.py
from django.urls import path
from .views import *

app_name = 'remgt'

urlpatterns=[
    path('', remgt_board_st, name='remgt_board_st'),
    path('re_cus/<int:pk>/', re_cus, name='re_cus'),
    path('<int:year>/<int:month>/<int:day>/', remgt_board, name='remgt_board'),
]

templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>

<body>
 <div class=""container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="nav">
            <li class="nav-item"><a href="/" class="navbar-brand">Home</a></li>
            <li class="nav-item"><a href="{% url 'remgt:remgt_board_st'%}" class="navbar-brand">반납관리</a></li>
            <li class="nav-item"><a href="{% url 'recovery:re_board' mn=0%}" class="navbar-brand">원상회복관리</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'input:file_list' %}" class="navbar-brand">파일 업로드</a></li>
            <li class="nav-item"><a href="#" class="nav-link">안녕하세요 {{user.get_username}}님~!</a></li>
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
            <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
            {% endif %}
        </ul>
    </nav>
 </div>

{% block content %}
{% endblock %}
</body>
</html>