config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('monitoring.urls')),
    path('upload/', include('input.urls')),
    path('recovery/', include('recovery.urls')),
    path('mgt/', include('remgt.urls')),
]

input/urls.py
from django.urls import path
from .views import *
from .models import Files

app_name = 'input'

urlpatterns=[
    path('', file_list, name='file_list'),
    path('upload/', FileUploadView.as_view(), name='file_upload'),
]

monitoring/urls.py
from django.urls import path
from .views import *
from .views2 import *
from .views3 import *

app_name = 'monitoring'

urlpatterns=[
    path('', ban_board, name='ban_board'),
    path('data/', search_list, name='search'),
    path('data/detail/<int:pk>/', DataDetailView.as_view(), name='detail'),
    path('data/update/<int:pk>/', DataUpdatelView.as_view(), name='data_update'),
    path('mass/', MassListView.as_view(), name='mass_board'),
    path('mass/add/', MassCreateView.as_view(), name='add'),
    path('mass/update/<int:pk>/', MassUpdateView.as_view(), name='update'),
    path('mass/delete/<int:pk>/', MassDeleteView.as_view(), name='delete'),
    #path('mi/', mibe_board, name='mibe_board'),
    #path('be/', be_board, name='be_board'),
    path('loading/', loading, name='loading')
]

recovery/urls.py
from django.urls import path
from .views import *

app_name = 'recovery'

urlpatterns=[
    path('<int:mn>/', re_board, name='re_board'),
    path('create/<int:pk>/', recovery_create, name='re_create'),
    path('update/<int:pk>/', RecoveryUpdatelView.as_view(), name='re_update'),
    path('delete/<int:pk>/', recovery_delete, name='re_delete'),
    path('detail/<int:pk>/', recovery_detail, name='re_detail'),
    path('mgt/detail/<int:pk>/', mgt_detail, name='mgt_detail'),
    path('mgt/create/<int:pk>/', mgt_create, name='mgt_create'),
    path('mgt/update/<int:pk>/', MgtUpdatelView.as_view(), name='mgt_update'),
    path('mgt/delete/<int:pk>/', mgt_delete, name='mgt_delete'),
]

remgt/urls.py
from django.urls import path
from .views import *

app_name = 'remgt'

urlpatterns=[
    path('', remgt_board_st, name='remgt_board_st'),
    path('re_cus/<int:pk>/', re_cus, name='re_cus'),
    path('<int:year>/<int:month>/<int:day>/', remgt_board, name='remgt_board'),
]

monitoring/models.py
from django.db import models
# Create your models here.

class CarTypeMgt(models.Model):
    num = models.IntegerField(default=0, null=True, blank=True, verbose_name="순번")
    cartype = models.CharField(max_length=10, null=True, verbose_name="차종")
    maxprice = models.IntegerField(default=0, null=True, blank=True, verbose_name="보험수리 기준금액")
    created = models.DateTimeField(auto_now_add=True, verbose_name="등록일자")
    updated = models.DateTimeField(auto_now=True, verbose_name="수정일자")

    class Meta:
        ordering = ['num']
        verbose_name = '차종관리'
        verbose_name_plural = '차종관리'


class Data(models.Model):
    a_rdate = models.DateField()
    fwc_num = models.CharField(max_length=30, null=True, blank=True)

    car_id = models.CharField(max_length=30, null=True, blank=True)
    car_num1 = models.CharField(max_length=20, null=True, help_text="원차량번호")
    car_num2 = models.CharField(max_length=20, null=True, help_text="반납차량번호")
    car_num3 = models.CharField(max_length=20, null=True, help_text="변경차량호")
    car_type = models.CharField(max_length=100, null=True, blank=True)
    car_model = models.CharField(max_length=100, null=True, blank=True, verbose_name="세부모델")
    car_sdate = models.DateField(null=True, blank=True, verbose_name='최초등록일')
    car_year = models.CharField(max_length=10, null=True, blank=True, verbose_name='연식')
    car_cor = models.CharField(max_length=20, null=True, blank=True, verbose_name='색상')
    car_price = models.IntegerField(default=0, verbose_name='차량가격')
    car_dc = models.IntegerField(default=0)
    car_ms = models.CharField(max_length=10, null=True, blank=True)
    car_ap = models.CharField(max_length=200, null=True, blank=True, verbose_name='주요옵션1')
    car_ap2 = models.CharField(max_length=200, null=True, blank=True, verbose_name='주요옵션2')
    car_acd = models.CharField(max_length=150, null=True, blank=True, verbose_name='사고내역')

    fwc_sdate = models.DateField(null=True, blank=True)
    fwc_stdprice = models.IntegerField(default=0)
    fwc_limm = models.IntegerField(default=0, null=True, blank=True)
    fwc_pr_code = models.CharField(max_length=10, null=True, blank=True)
    fwc_pt_dept = models.CharField(max_length=20, null=True, blank=True)
    fwc_pt_dept_mgr = models.CharField(max_length=20, null=True, blank=True)
    fwc_3pt = models.CharField(max_length=20, null=True, blank=True)

    a_limm = models.IntegerField(default=0, verbose_name='주행거리')
    cus_name = models.CharField(max_length=100, null=True, blank=True)
    cus_add = models.CharField(max_length=100, null=True, blank=True)
    cus_add2 = models.CharField(max_length=100, null=True, blank=True)
    a_type = models.CharField(max_length=20, null=True, blank=True)
    a_mgr = models.CharField(max_length=20, null=True, blank=True)
    a_spot = models.CharField(max_length=100, null=True, blank=True)
    a_move = models.CharField(max_length=30, null=True, blank=True)
    text = models.TextField(blank=True, null=True, verbose_name='비고')
    ex = models.BooleanField(default=False, verbose_name="원상회복대상")
    cx = models.BooleanField(default=False, verbose_name="인증대상")
    cus_ctn = models.CharField(max_length=100, null=True, blank=True)
    typelink = models.ForeignKey(CarTypeMgt, null=True, on_delete=models.SET_NULL)


from django.contrib.auth.models import User
from django.urls import reverse

class MassBoard(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='mass_board')
    fdate = models.DateField(blank=True, null=True, verbose_name="반납(예정)일", help_text="날짜 형식은 'YYYY-MM-DD' 입니다.")
    cus = models.CharField(max_length=50, blank=True, null=True, verbose_name="고객명")
    car = models.CharField(max_length=50, blank=True, null=True, verbose_name="차명")
    num = models.IntegerField(default=0, verbose_name="대수")
    spot = models.CharField(max_length=50, blank=True, null=True, verbose_name="반납(예정)지")
    text = models.TextField(blank=True, null=True, verbose_name="비고")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-fdate']
        verbose_name = 'mass'
        verbose_name_plural = 'mass'

    def get_absolute_url(self):
        return reverse('monitoring:mass_board', args = [str(self.id)])

monitoring/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.contrib.auth.decorators import login_required

import boto3
import io
import pandas as pd
import xlrd as rd
import openpyxl as xl
from django.conf import settings
from config import asset_storage
from input.models import Files
from .models import Data
from django.db.models import Max, Min, Sum
import datetime


@login_required

def loading(request):

    aws_access_key_id = settings.AWS_ACCESS_KEY_ID
    aws_secret_access_key = settings.AWS_SECRET_ACCESS_KEY
    bucket = settings.AWS_STORAGE_BUCKET_NAME

    file = Files.objects.all()[0]
    key1 = file.file.name
    key2 = asset_storage.FileStorage.location
    key = key2+'/'+key1

    s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key)
    obj = s3.get_object(Bucket=bucket, Key=key)

    data = obj['Body'].read()
    #df = pd.read_excel(io.BytesIO(data), encoding='utf-8')
    df = xl.load_workbook(io.BytesIO(data))
    sheet = df['Sheet1']

    cp = '2100-01-01'
    cp = datetime.datetime.strptime(cp, "%Y-%m-%d").date()
    for i in range(2, sheet.max_row+1):
        a_rdate = sheet.cell(i, 2).value
        a_rdate = datetime.datetime.strptime(a_rdate, "%Y-%m-%d").date()
        if cp >= a_rdate: cp = a_rdate
    #print("@@@@@@@@@@",cp)
    #datas = Data.objects.aggregate(a_rdate = Min('a_rdate'))

    dp = cp + datetime.timedelta(days=1)

    datas = Data.objects.filter(a_rdate__gte=dp)
    datas.delete()

    #a = sheet.cell(4,2).value
    #a = datetime.datetime.strptime(a, "%Y-%m-%d").date()
    #print(type(a),a)
    for i in range(2, sheet.max_row +1):
        a_rdate = sheet.cell(i,2).value
        a_rdate = datetime.datetime.strptime(a_rdate, "%Y-%m-%d").date()
        car_num2 = sheet.cell(i, 3).value
        car_num3 = sheet.cell(i, 4).value
        car_num1 = sheet.cell(i, 5).value
        fwc_sdate = sheet.cell(i, 6).value
        try:
            fwc_sdate = datetime.datetime.strptime(fwc_sdate, "%Y-%m-%d").date()
        except:
            fwc_sdate = None
        car_type = sheet.cell(i, 7).value
        car_year = sheet.cell(i, 8).value
        car_model = sheet.cell(i, 9).value
        car_cor = sheet.cell(i,10).value
        a_limm = int(sheet.cell(i, 11).value)
        cus_name = sheet.cell(i, 12).value
        cus_add = sheet.cell(i, 13).value
        cus_add2 = sheet.cell(i, 14).value
        a_type = sheet.cell(i, 15).value
        car_price = int(sheet.cell(i, 16).value)
        car_dc = int(sheet.cell(i, 17).value)
        fwc_stdprice = int(sheet.cell(i, 18).value)
        fwc_limm = int(sheet.cell(i, 19).value)
        fwc_pr_code = sheet.cell(i, 20).value
        fwc_pt_dept = sheet.cell(i, 21).value
        fwc_3pt = sheet.cell(i, 22).value
        a_mgr = sheet.cell(i, 23).value
        fwc_pt_dept_mgr = sheet.cell(i, 24).value
        car_ms =sheet.cell(i, 25).value
        text = sheet.cell(i, 31).value
        a_spot = sheet.cell(i,32).value
        a_move = sheet.cell(i, 33).value
        car_ap = sheet.cell(i, 35).value
        car_ap2 = sheet.cell(i, 36).value
        car_acd = sheet.cell(i, 37).value
        car_sdate = sheet.cell(i, 38).value

        try :
            car_sdate = datetime.datetime.strptime(car_sdate, "%Y-%m-%d").date()
        except:
            car_sdate = None

        try :
            data = Data.objects.get(a_rdate=a_rdate, car_num2=car_num2)
            data.a_rdate = a_rdate
            data.car_num2 = car_num2
            data.car_num3 = car_num3
            data.car_num1 = car_num1
            data.fwc_sdate = fwc_sdate
            data.car_type = car_type
            data.car_year = car_year
            data.car_model = car_model
            data.car_cor = car_cor
            data.a_limm = a_limm
            data.cus_name = cus_name
            data.cus_add = cus_add
            data.cus_add2 = cus_add2
            data.a_type = a_type
            data.car_price = car_price
            data.car_dc = car_dc
            data.fwc_stdprice =fwc_stdprice
            data.fwc_limm = fwc_limm
            data.fwc_pr_code = fwc_pr_code
            data.fwc_pt_dept = fwc_pt_dept
            data.fwc_3pt = fwc_3pt
            data.a_mgr = a_mgr
            data.fwc_pt_dept_mgr = fwc_pt_dept_mgr
            data.car_ms = car_ms
            data.text = text
            data.a_spot = a_spot
            data.a_move = a_move
            data.car_ap = car_ap
            data.car_ap2 = car_ap2
            data.car_acd = car_acd
            data.car_sdate = car_sdate
            data.save()
        except :
            data = Data(
                a_rdate = a_rdate,
                car_num2 = car_num2,
                car_num3 = car_num3,
                car_num1 = car_num1,
                fwc_sdate = fwc_sdate,
                car_type = car_type,
                car_year = car_year,
                car_model = car_model,
                car_cor = car_cor,
                a_limm = a_limm,
                cus_name = cus_name,
                cus_add = cus_add,
                cus_add2 = cus_add2,
                a_type = a_type,
                car_price = car_price,
                car_dc = car_dc,
                fwc_stdprice = fwc_stdprice,
                fwc_limm = fwc_limm,
                fwc_pr_code = fwc_pr_code,
                fwc_pt_dept = fwc_pt_dept,
                fwc_3pt = fwc_3pt,
                a_mgr = a_mgr,
                fwc_pt_dept_mgr = fwc_pt_dept_mgr,
                car_ms = car_ms,
                text = text,
                a_spot = a_spot,
                a_move = a_move,
                car_ap = car_ap,
                car_ap2 = car_ap2,
                car_acd = car_acd,
                car_sdate = car_sdate
            )
            data.save()

        #print(a_rdate, car_num2)
        #Data.a_rdate = sheet.cell(i, 2).value
        #Data.save()

    #cell = sheet.cell(3, 4).value
    #print("@@@@@@@@@@ 값은? ", sheet.max_row)

    return redirect('/')

monitoring/templates/monitoring/be_board.html
{% extends "layout.html" %}
{% block title %}
배정 현황
{% endblock %}

{% block content %}
작성
{% endblock %}

monitoring/templates/monitoring/data_detail.html
{% extends "layout.html" %}

{% block title %}Detail{% endblock %}

{% block content %}
{% load humanize %}
<div class="container"></div>
<p></p>

<div class="container">
    <a href="{% url 'monitoring:data_update' pk=object.id %}" class="btn btn-danger btn-sm">차량정보 수정</a>
    {% if object.fwc_3pt == "글로비스" %}
    <span class="badge badge-danger">글로비스</span>
    {% endif %}
    <a href="{% url 'remgt:re_cus' pk=object.id %}" class="btn btn-success btn-sm">반납관리</a>
    {% if object.ex %}
    <a href="{% url 'recovery:re_detail' pk=object.id %}" class="btn btn-primary btn-sm">원상회복관리</a>
    <span class="badge badge-secondary">대상</span>
    {% else %}
    <a href="{% url 'recovery:re_create' pk=object.id %}" class="btn btn-primary btn-sm">원상회복관리</a>
    <span class="badge badge-secondary">미대상</span>
    {% endif %}

</div>


<p></p>

<div class="container">
<span style="font-size:0.8em">
<dl class="row">
    <dt class="col-sm-3">고유번호</dt>
    <dd class="col-sm-9">
        <dl class="row">
          <dt class="col-sm-3">차대번호</dt>
          <dd class="col-sm-9">{{object.car_id}}</dd>

          <dt class="col-sm-3">대출계약번호</dt>
          <dd class="col-sm-9">{{object.fwc_num}}</dd>
        </dl>
    </dd>

    <dt class="col-sm-3">차량번호</dt>
    <dd class="col-sm-9">
      <dl class="row">
          <dt class="col-sm-3">최초(원)번호</dt>
          <dd class="col-sm-9">{{object.car_num1}}</dd>

          <dt class="col-sm-3">반납시점</dt>
          <dd class="col-sm-9">{{object.car_num2}}</dd>

          <dt class="col-sm-3">변경 번호</dt>
          <dd class="col-sm-9">{{object.car_num3}}</dd>
      </dl>

    <dt class="col-sm-3">차종(모델)</dt>
    <dd class="col-sm-9">{{object.car_type}}</dd>

    <dt class="col-sm-3">세부모델</dt>
    <dd class="col-sm-9">{{object.car_model}}</dd>

    <dt class="col-sm-3">연식</dt>
    <dd class="col-sm-9">{{object.car_year}} 년</dd>

    <dt class="col-sm-3">최초등록일</dt>
    <dd class="col-sm-9">{{object.car_sdate|date:'Y-m-d'}}</dd>

    <dt class="col-sm-3">차량가격</dt>
    <dd class="col-sm-9">{{object.car_price|intcomma}}</dd>

    <dt class="col-sm-3">할인가격</dt>
    <dd class="col-sm-9">{{object.car_dc|intcomma}}</dd>

    <dt class="col-sm-3">주요옵션</dt>
    <dd class="col-sm-9">
        <p>{{object.car_ap}}</p>
        <p>{{object.car_ap2}}</p>
    </dd>

    <dt class="col-sm-3">반납관련정보</dt>
    <dd class="col-sm-9">
      <dl class="row">
          <dt class="col-sm-3">반납일</dt>
          <dd class="col-sm-9">{{object.a_rdate|date:'Y-m-d'}}</dd>
          <dt class="col-sm-3">반납유형</dt>
          <dd class="col-sm-9">{{object.a_type}}</dd>
          <dt class="col-sm-3">반납주행거리</dt>
          <dd class="col-sm-9">{{object.a_limm|intcomma}}</dd>
          <dt class="col-sm-3">사고내역</dt>
          <dd class="col-sm-9">{{object.car_acd}}</dd>
          <dt class="col-sm-3">반납지</dt>
          <dd class="col-sm-9">{{object.a_spot}}</dd>
          <dt class="col-sm-3">반납담당자</dt>
          <dd class="col-sm-9">{{object.a_mgr}}</dd>
          <dt class="col-sm-3">원상회복 유/무</dt>
          {% if object.ex is True %}
          <dd class="col-sm-9">Yes</dd>
          {% else %}
          <dd class="col-sm-9">No</dd>
          {% endif %}
      </dl>
    </dd>

    <dt class="col-sm-3">계약관련정보</dt>
    <dd class="col-sm-9">
      <dl class="row">
          <dt class="col-sm-3">선물사</dt>
          {% if object.fwc_3pt == "글로비스" %}
            <span class="col-sm-2 badge badge-danger">글로비스</span>
            <dd class="col-sm-7"></dd>
          {% else %}
          <dd class="col-sm-9">{{object.fwc_3pt}}</dd>
          {% endif %}
          <dt class="col-sm-3">잔가기준가격</dt>
          <dd class="col-sm-9">{{object.fwc_stdprice|intcomma}}</dd>
          <dt class="col-sm-3">계약시작일</dt>
          <dd class="col-sm-9">{{object.fwc_sdate|date:'Y-m-d'}}</dd>
          <dt class="col-sm-3">약정주행거리</dt>
          <dd class="col-sm-9">{{object.fwc_limm|intcomma}}</dd>
          <dt class="col-sm-3">상품코드</dt>
          <dd class="col-sm-9">{{object.fwc_pr_code}}</dd>
          <dt class="col-sm-3">거래처관리구분</dt>
          <dd class="col-sm-9">{{object.fwc_pt_dept}}</dd>
          <dt class="col-sm-3">이용고객</dt>
          <dd class="col-sm-9">{{object.cus_name}}</dd>
          <dt class="col-sm-3">고객연락처</dt>
          <dd class="col-sm-9">{{object.cus_ctn}}</dd>
          <dt class="col-sm-3">고객주소1</dt>
          <dd class="col-sm-9">{{object.cus_add}}</dd>
          <dt class="col-sm-3">고객주소2</dt>
          <dd class="col-sm-9">{{object.cus_add2}}</dd>
          <dt class="col-sm-3">HCS 담당자</dt>
          <dd class="col-sm-9">{{object.fwc_pt_dept_mgr}}</dd>

      </dl>
    </dd>

    <dt class="col-sm-3">비고</dt>
    <dd class="col-sm-9">{{object.text}}</dd>
</dl>
</span>
</div>


<div class="container">
</div>

<p></p>

<div class="container">

        <form class="form-inline" action="{%url 'monitoring:search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="차량번호" aria-label="Search" name="number" value="{{number}}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
        </form>
</div>
<p></p>

{% endblock %}

monitoring/templates/monitoring/data_list.html
{% extends "layout.html" %}

{% block title %}대상 차량 리스트{% endblock %}

{% block content %}

<p></p>
<div class="col-md-4">

        <form class="form-inline" action="{%url 'monitoring:search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="차량번호" aria-label="Search" name="number" value="{{number}}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색</button>
        </form>
</div>
<p></p>

<div class="container">
<font size="2">
<table class="table table-striped">
    {% if list %}
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">반납(예상)일</th>
            <th scope="col">원차량번호</th>
            <th scope="col">반납차량번호</th>
            <th scope="col">변경차량번호</th>
            <th scope="col">차종(모델)</th>
            <th scope="col">세부모델</th>
            <th scope="col"></th>
            <th scope="col">원상회복대상 여부</th>
        </tr>
    </thead>
    <tbody>
        {% for car in list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{car.a_rdate|date:'Y-m-d'}}
                {% if car.fwc_3pt == "글로비스" %}
                    <p><span class="badge badge-danger">글로비스</span></p>
                {% endif %}
                </td>
                <td>{{car.car_num1}}</td>
                <td>{{car.car_num2}}</td>
                <td>{{car.car_num3}}</td>
                <td>{{car.car_type}}</td>
                <td>{{car.car_model}}</td>
                <td><a href="{% url 'monitoring:detail' pk=car.id %}" class="btn btn-dark btn-sm">상세보기</a>
                    <a href="{% url 'remgt:re_cus' pk=car.id %}" class="btn btn-success btn-sm">반납관리</a>
                {% if car.ex %}
                <td><span class="badge badge-secondary">대상</span> <a href="{% url 'recovery:re_detail' pk=car.id %}" class="btn btn-primary btn-sm">관리</a></td></td>
                {% else %}
                <td><a href="{% url 'recovery:re_create' pk=car.id %}" class="btn btn-primary btn-sm">신규등록</a></td></td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    {% else %}
    <thead>
        <tr>
            <th scope="col">반납 데이터가 없습니다. 차량을 확인해 주세요.</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href="{% url 'monitoring:ban_board'%}" class="btn btn-danger btn-sm">확인</a></td>
        </tr>
    </tbody>
    {% endif %}
</table>
</font>
</div>

{% if is_paginated %}
<ul class="pagination justify-content-center pagination-sm">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'monitoring:mass_board' %}?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
    {% endif %}

    {% for object in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
            <a class="page-link" href="{{request.path}}?page={{forloop.counter}}">{{forloop.counter}}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'monitoring:mass_board' %}?page={{page_obj.next_page_number}}">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

monitoring/templates/monitoring/data_update.html
{% extends "layout.html" %}

{% block title %}수정{% endblock %}

{% block content %}

<div class="container">
<span style="font-size:1em">
<dl class="row">
    <dt class="col-sm-3">고유번호</dt>
    <dd class="col-sm-9">
        <dl class="row">
          <dt class="col-sm-3">차대번호</dt>
          <dd class="col-sm-9">{{object.car_id}}</dd>

          <dt class="col-sm-3">대출계약번호</dt>
          <dd class="col-sm-9">{{object.fwc_num}}</dd>
        </dl>
    </dd>

    <dt class="col-sm-3">차량번호</dt>
    <dd class="col-sm-9">
      <dl class="row">
          <dt class="col-sm-3">최초(원)번호</dt>
          <dd class="col-sm-9">{{object.car_num1}}</dd>

          <dt class="col-sm-3">반납시점</dt>
          <dd class="col-sm-9">{{object.car_num2}}</dd>

          <dt class="col-sm-3">변경 번호</dt>
          <dd class="col-sm-9">{{object.car_num3}}</dd>
      </dl>

    <dt class="col-sm-3">차종(모델)</dt>
    <dd class="col-sm-9">{{object.car_type}}</dd>

</dl>
</span>
</div>
<p></p>
<div class="container">
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update" class="btn btn-info btn-sm">
</form>
</div>
{% endblock %}

monitoring/templates/monitoring/massboard_list.html
{% extends "layout.html" %}

{% block title %}대량반납 현황{% endblock %}

{% block content %}

<p></p>
<div class="col-md-2">
<div class="btn-group">
    <a href="{% url 'monitoring:add' %}" class="btn btn-info">대량반납 추가</a>
</div>
</div>
<p></p>

<div class="container">
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">반납(예상)일</th>
            <th scope="col">고객</th>
            <th scope="col">차량</th>
            <th scope="col">대수</th>
            <th scope="col">반납(예정)지</th>
            <th scope="col">비고</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for mass in object_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{mass.fdate|date:'Y-m-d'}}</td>
                <td>{{mass.cus}}</td>
                <td>{{mass.car}}</td>
                <td>{{mass.num}}</td>
                <td>{{mass.spot}}</td>
                <td>{{mass.text}}</td>
                <td><a href="{% url 'monitoring:update' pk=mass.id %}" class="btn btn-success btn-sm">Modify</a> </td>
                <td><a href="{% url 'monitoring:delete' pk=mass.id %}" class="btn btn-danger btn-sm">Delete</a> </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% if is_paginated %}
<ul class="pagination justify-content-center pagination-sm">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'monitoring:mass_board' %}?page={{page_obj.previous_page_number}}" tabindex="-1">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
    {% endif %}

    {% for object in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
            <a class="page-link" href="{{request.path}}?page={{forloop.counter}}">{{forloop.counter}}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'monitoring:mass_board' %}?page={{page_obj.next_page_number}}">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

monitoring/templates/monitoring/mibe_board.html
{% extends "layout.html" %}
{% block title %}
미배정 현황
{% endblock %}

{% block content %}
작성중
{% endblock %}