config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('monitoring.urls')),
    path('upload/', include('input.urls')),
    path('recovery/', include('recovery.urls')),
    path('mgt/', include('remgt.urls')),
]

input/urls.py
from django.urls import path
from .views import *
from .models import Files

app_name = 'input'

urlpatterns=[
    path('', file_list, name='file_list'),
    path('upload/', FileUploadView.as_view(), name='file_upload'),
]

input/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse

class Files(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='user_files')
    file = models.FileField(upload_to='반납데이터')
    text = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']
        verbose_name = 'file'
        verbose_name_plural = 'files'

    def __str__(self):
        return self.file.name + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('input:file_list', args=[str(self.id)])

input/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from config import asset_storage

# Create your views here.

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Files

@login_required

def file_list(request):
    files = Files.objects.all()[:10]
    return render(request, 'input/file_list.html', {'files':files})

from django.views.generic.edit import CreateView

class FileUploadView(LoginRequiredMixin,  CreateView):
    model = Files
    fields = ['file', 'text']
    template_name = 'input/upload.html'


    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/loading')
        else:
            return self.render_to_response({'form':form})

input/templates/input/file_list.html
{% extends "layout.html" %}
{% block title %}
파일관리
{% endblock %}

{% block content %}

<p></p>
<div class="col-md-2">
<div class="btn-group">
    <a href="{% url 'input:file_upload' %}" class="btn btn-info">Upload</a>
</div>
</div>
<p></p>


<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>#</B></td>
            <td><B>파일명</B></td>
            <td><B>비고</B></td>
            <td><B>파일 생성일</B></td>
            <td><B></B></td>
        </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td><a href="{{file.file.url}}">{{file.file}}</a></td>
            <td>{{file.text}}</td>
            <td>{{file.updated}}</a></td>
            <td>{{file.author}}</a></td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
</div>

{% endblock %}

input/templates/input/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>

</body>
</html>